---
services:
  developer-sandbox:
    container_name: developer-sandbox
    image: ghcr.io/jgfranco17/developer-sandbox:latest
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
