name: Docker

on:
  push:
    branches:
      - "main"
    paths:
      - "project.json"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_GITHUB_USER }}
          password: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Get image details
        id: image
        run: |
          VERSION=$(jq -r '.version' project.json)
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/${{ matrix.os }}-sandbox
          echo "name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          tags: |
            ${{ steps.image.outputs.name }}:latest
            ${{ steps.image.outputs.name }}:${{ steps.image.outputs.version }}
