name: Docker

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.CI_GITHUB_USER }}
          password: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Set image name
        id: image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/developer-sandbox
          echo "name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ steps.image.outputs.name }}:latest
            ${{ steps.image.outputs.name }}:${{ github.sha }}
